### ISSUE TITLE
gen.array(gen.any) takes super long

### ISSUE THREAD

**Issue by jethrolarson** [leebyron/testcheck-js#61] opened 2017-11-15 22:35 UTC
Single test (using mocha-testcheck) that takes gen.array(gen.any) never completes. Mocha times out the browser locks up. Are these not safe to use together?

**Comment by leebyron** [comment] 2018-03-19 20:35
It would be helpful if you could provide a more complete failing test case.

The following test seems to complete in <5ms

```sh
❯ time node -p "var {gen, sample} = require('testcheck'); sample(gen.array(gen.any));"

[ [],
  [],
  [ [ [Array] ] ],
  [ [ [Object], [Object] ] ],
  [ {}, {}, [ false ] ],
  [ [ [Object] ], { '9Q': [Object], Y4w: [] } ],
  [ { d: [] } ],
  [ { '4': [Object], Nie: {} }, [], [ [Array] ], {}, { QI: [] } ],
  [ { '1': [Array] },
    { mH: [Object], j: [Object] },
    [ [Array], {} ],
    [ [Array] ],
    { FI: [Array], Tn: [] } ],
  [ {}, { '6E': 6 }, {}, {}, { YX9: [Object], BA: {} } ] ]
node -p   0.19s user 0.04s system 108% cpu 0.215 total
```

Note that `gen.any` produces values which may include nested arrays and objects. Objects are particularly expensive to generate since the key strings are randomly generated as well.

**Comment by jethrolarson** [comment] 2018-03-19 21:12
Maybe it's something to do with mocha. I'll see if I still have that branch somewhere

**Comment by leebyron** [comment] 2018-03-26 19:27
I'm going to close this issue for now - but feel free to re-open if you come across a reproducible case we can look at together.

**Closed by leebyron** 2018-03-26 19:27 UTC
